### ISSUE TITLE
DataStrean Error

### ISSUE THREAD

**Issue by sMuve** [SirBitesalot/AvorionServerManager#5]
Hi there :)

I tried to use my existing galaxy and every time the AvorionServerManager gives me the following output:

`04:09:38:503 Enabled Traces: 

04:09:38:506 Avorion server Beta 0.10.2 r7448 running on Windows 8.1+ starting up in 
"D:\avorionserver\galaxies\Homeland"

04:09:38:508 CPU: GenuineIntel 8 Cores

04:09:38:509 name: Schattenwoelfe

04:09:38:511 seed: 2YuSRZSF

04:09:38:513 port: 7783

04:09:38:514 max online players: 10

04:09:38:515 save interval: 600

04:09:38:516 broadcast interval: 5

04:09:38:517 max loaded sector time: 300

04:09:38:518 weak update: yes

04:09:38:519 worker threads: 2

04:09:38:520 difficulty: Veteran

04:09:38:521 infiniteResources: no

04:09:38:523 collision: 0

04:09:38:524 access list: Blacklist

04:09:38:526 public: yes

04:09:38:527 authentication: no

04:09:38:528 listed: no

04:09:38:530 steam networking: yes

04:09:38:531 administrators: '' 'admin' 

04:09:38:532 An exception occurred: DataStream access error: Accessed data exceeds buffer size: 16101, offset: 16101, access size: 1`

I tried to turn on/off some settings and add more threads etc. but without any success.

The error only appears when I use an existing galaxy. I've choosen the path "D:\avorionserver\galaxies" and the galaxy name "Homeland" and entered the Seed from my old server.ini.

Any help would be appreciated :)

Kind regards
sMuve

**Comment by SirBitesalot** [comment]
@sMuve 
It seems like the error occures in the server process.
Does the same galaxy work without the Manager?
If i try to load an existing galaxy it seems to work.

If you upload you galaxy folder I could analyze this further.

**Comment by sMuve** [comment]
@SirBitesalot 
It doesn't work without the manager, but the galaxy worked under linux and with the Linux Server Manager for Avorion without any problems :-/

The manager works flawless, if I use a new galaxy.

Here is a screenshot of my settings:
[imgur](http://imgur.com/a/APSRw)

I shall mention that I firstly used the random generated seed and set the path & galaxy name. Then I recognized, that the galaxy won't load correct and that the seed was a diffrent one than my galaxy had and I wasn't able to change it.
My conclusion was to reinstall the ASM, copy the seed from my existing galaxy and set the path & galaxy name again plus the seed, but that didn't solve the problem :-/

Where shall I upload my galaxy for you ?

Thanks in advance!

**Comment by SirBitesalot** [comment]
@sMuve 
Could be an issue with the Avorion Server.
I will look into this in case it is caused by the manager or there is a way to fix galaxy files.
You can use any file sharing service you like,
For example:
[Dropbox](https://www.dropbox.com)
[Google Drive](https://drive.google.com)
[File Dropper](http://filedropper.com/)

**Comment by sMuve** [comment]
Here it is:
[Google Drive](https://drive.google.com/file/d/0B88xsfhpJkQTUkhMcWEwNEFfTjQ/view)

**Comment by SirBitesalot** [comment]
After testing for some time I have found out that the error is caused by two missing files (jumps.dat and jumpsmeta.dat).
After adding dummy files (createt from new server with same settings) the server started and I was able to connect.
You said you hosted the server previously on linux. ~~Maybe the linux server does not generated them?~~ 
I started an avorion server on linux and the files where generated.
Maybe you lost them while copying the server over to windows?

I attached a folder that contains the two dummy files I used. Place them in the root folder of your galaxy ("Homeland" in this case)
[DummyJumps.zip](https://github.com/SirBitesalot/AvorionServerManager/files/852710/DummyJumps.zip)
Can you try if this works for you so I can close this issue?

**Comment by sMuve** [comment]
@SirBitesalot
Seems to work :-)

**Comment by sMuve** [comment]
Thank you very much!!! We appreciate your help so much!
